version: "2"
checks:
  argument-count:
    config:
      threshold: 6
exclude_patterns:
  - "src/main/java/com/autonomouslogic/dynamomapper/DynamoMapper.java"
  - "src/main/java/com/autonomouslogic/dynamomapper/DynamoAsyncMapper.java"
